-- Add upload-level provenance and rerun protection for the DesFert stems ETL.
-- Apply to a restored test database before running populate_database.qmd.

BEGIN;

CREATE TABLE IF NOT EXISTS urbancndep.stems_upload_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file text NOT NULL,
  source_md5 text NOT NULL,
  survey_start date NOT NULL,
  survey_end date NOT NULL,
  row_counts jsonb NOT NULL,
  completed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stems_upload_log_source_md5_uq UNIQUE (source_md5),
  CONSTRAINT stems_upload_log_survey_order_check
    CHECK (survey_end >= survey_start)
);

COMMENT ON TABLE urbancndep.stems_upload_log IS
  'One row per successfully committed KoBo stems export; source_md5 prevents accidental reruns.';

COMMENT ON COLUMN urbancndep.stems_upload_log.row_counts IS
  'Affected-row accounting captured in the same transaction as the upload.';

COMMIT;
